---
- hosts: all
  vars:
    concourse_apps:
      - fly
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - include_tasks: test-fly.yml
- hosts: all
  vars:
    concourse_apps:
      - concourse
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - include_tasks: test-concourse.yml
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - include_tasks: test-fly.yml
    - include_tasks: test-concourse.yml
