---
- name: Executing 'concourse --version'
  ansible.builtin.command: /usr/local/bin/concourse --version
  changed_when: false
  register: concourse_test_output
- name: Output of 'concourse --version'
  ansible.builtin.debug:
    msg: '{{ concourse_test_output.stdout }}'
