---
- name: Testing andrewrothstein.concourse (fly)
  hosts: all
  vars:
    concourse_apps:
      - fly
  tasks:
    - name: Installing andrewrothstein.concourse (fly)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing fly
      ansible.builtin.include_tasks: test-fly.yml
- name: Testing andrewrothstein.concourse (concourse)
  hosts: all
  vars:
    concourse_apps:
      - concourse
  tasks:
    - name: Installing andrewrothstein.concourse (concourse)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing concourse
      ansible.builtin.include_tasks: test-concourse.yml
- name: Testing andrewrothstein.concourse
  hosts: all
  tasks:
    - name: Installing andrewrothstein.concourse
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing fly
      ansible.builtin.include_tasks: test-fly.yml
    - name: Testing concourse
      ansible.builtin.include_tasks: test-concourse.yml
