---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/concourse --version
      register: concourse_test_output
    - name: concourse --version
      debug:
        msg: '{{ concourse_test_output.stdout }}'
    - command: /usr/local/bin/fly --version
      register: fly_test_output
    - name: fly --version
      debug:
        msg: '{{ fly_test_output.stdout }}'
